---
description: "#{repo}"
builds:
- platform: "debian8"
  arch: "amd64"
  asset_filename: "monitoring-plugins-debian8_linux_amd64_#{version}.tar.gz"
  sha_filename: "#{repo}_#{version}_sha512-checksums.txt"
  filter:
  - "entity.system.os == 'linux'"
  - "entity.system.platform_family == 'debian'"
  - "entity.system.platform_version.split('.')[0] == '8'"
  - "entity.system.arch == 'amd64'"

