---
description: "#{repo}"
builds:
- platform: "alpine"
  arch: "amd64"
  asset_filename: "monitoring-plugins-alpine_linux_amd64_#{version}.tar.gz"
  sha_filename: "#{repo}_#{version}_sha512-checksums.txt"
  filter:
  - "entity.system.os == 'linux'"
  - "entity.system.platform == 'alpine'"
  - "entity.system.arch == 'amd64'"

- platform: "amazon1"
  arch: "amd64"
  asset_filename: "monitoring-plugins-debian8_linux_amd64_#{version}.tar.gz"
  sha_filename: "#{repo}_#{version}_sha512-checksums.txt"
  filter:
  - "entity.system.os == 'linux'"
  - "entity.system.platform == 'amazon'"
  # Amazon Linux 1 uses versions of the format YYYY.MM starting from 2011 and going until 2018
  # thus we are matching if the YYYY portion of platform_version contains '201'
  - "entity.system.platform_version.split('.')[0].indexOf('201') !== -1"
  - "entity.system.arch == 'amd64'"

- platform: "amazon2"
  arch: "amd64"
  asset_filename: "monitoring-plugins-debian8_linux_amd64_#{version}.tar.gz"
  sha_filename: "#{repo}_#{version}_sha512-checksums.txt"
  filter:
  - "entity.system.os == 'linux'"
  - "entity.system.platform == 'amazon'"
  - "entity.system.platform_version == '2'"
  - "entity.system.arch == 'amd64'"

- platform: "centos6"
  arch: "amd64"
  asset_filename: "monitoring-plugins-centos6_linux_amd64_#{version}.tar.gz"
  sha_filename: "#{repo}_#{version}_sha512-checksums.txt"
  filter:
  - "entity.system.os == 'linux'"
  - "entity.system.platform_family == 'rhel'"
  - "entity.system.platform_version.split('.')[0] == '6'"
  - "entity.system.arch == 'amd64'"

- platform: "centos7"
  arch: "amd64"
  asset_filename: "monitoring-plugins-debian8_linux_amd64_#{version}.tar.gz"
  sha_filename: "#{repo}_#{version}_sha512-checksums.txt"
  filter:
  - "entity.system.os == 'linux'"
  - "entity.system.platform_family == 'rhel'"
  - "entity.system.platform_version.split('.')[0] == '7'"
  - "entity.system.arch == 'amd64'"

- platform: "centos8"
  arch: "amd64"
  asset_filename: "monitoring-plugins-debian8_linux_amd64_#{version}.tar.gz"
  sha_filename: "#{repo}_#{version}_sha512-checksums.txt"
  filter:
  - "entity.system.os == 'linux'"
  - "entity.system.platform_family == 'rhel'"
  - "entity.system.platform_version.split('.')[0] == '8'"
  - "entity.system.arch == 'amd64'"

- platform: "debian8"
  arch: "amd64"
  asset_filename: "monitoring-plugins-debian8_linux_amd64_#{version}.tar.gz"
  sha_filename: "#{repo}_#{version}_sha512-checksums.txt"
  filter:
  - "entity.system.os == 'linux'"
  - "entity.system.platform_family == 'debian'"
  - "entity.system.platform_version.split('.')[0] == '8'"
  - "entity.system.arch == 'amd64'"

- platform: "debian9"
  arch: "amd64"
  asset_filename: "monitoring-plugins-debian8_linux_amd64_#{version}.tar.gz"
  sha_filename: "#{repo}_#{version}_sha512-checksums.txt"
  filter:
  - "entity.system.os == 'linux'"
  - "entity.system.platform_family == 'debian'"
  - "entity.system.platform_version.split('.')[0] == '9'"
  - "entity.system.arch == 'amd64'"

- platform: "debian10"
  arch: "amd64"
  asset_filename: "monitoring-plugins-debian8_linux_amd64_#{version}.tar.gz"
  sha_filename: "#{repo}_#{version}_sha512-checksums.txt"
  filter:
  - "entity.system.os == 'linux'"
  - "entity.system.platform_family == 'debian'"
  - "entity.system.platform_version.split('.')[0] == '10'"
  - "entity.system.arch == 'amd64'"

- platform: "debian11"
  arch: "amd64"
  asset_filename: "monitoring-plugins-debian8_linux_amd64_#{version}.tar.gz"
  sha_filename: "#{repo}_#{version}_sha512-checksums.txt"
  filter:
  - "entity.system.os == 'linux'"
  - "entity.system.platform_family == 'debian'"
  - "entity.system.platform_version.split('.')[0] == '11'"
  - "entity.system.arch == 'amd64'"

- platform: "ubuntu1404"
  arch: "amd64"
  asset_filename: "monitoring-plugins-debian8_linux_amd64_#{version}.tar.gz"
  sha_filename: "#{repo}_#{version}_sha512-checksums.txt"
  filter:
  - "entity.system.os == 'linux'"
  - "entity.system.platform == 'ubuntu'"
  - "entity.system.platform_version.split('.')[0] == '14'"
  - "entity.system.arch == 'amd64'"

- platform: "ubuntu1604"
  arch: "amd64"
  asset_filename: "monitoring-plugins-debian8_linux_amd64_#{version}.tar.gz"
  sha_filename: "#{repo}_#{version}_sha512-checksums.txt"
  filter:
  - "entity.system.os == 'linux'"
  - "entity.system.platform == 'ubuntu'"
  - "entity.system.platform_version.split('.')[0] == '16'"
  - "entity.system.arch == 'amd64'"

- platform: "ubuntu1804"
  arch: "amd64"
  asset_filename: "monitoring-plugins-debian8_linux_amd64_#{version}.tar.gz"
  sha_filename: "#{repo}_#{version}_sha512-checksums.txt"
  filter:
  - "entity.system.os == 'linux'"
  - "entity.system.platform == 'ubuntu'"
  - "entity.system.platform_version.split('.')[0] == '18'"
  - "entity.system.arch == 'amd64'"

- platform: "ubuntu2004"
  arch: "amd64"
  asset_filename: "monitoring-plugins-debian8_linux_amd64_#{version}.tar.gz"
  sha_filename: "#{repo}_#{version}_sha512-checksums.txt"
  filter:
  - "entity.system.os == 'linux'"
  - "entity.system.platform == 'ubuntu'"
  - "entity.system.platform_version.split('.')[0] == '20'"
  - "entity.system.arch == 'amd64'"

- platform: "ubuntu2204"
  arch: "amd64"
  asset_filename: "monitoring-plugins-debian8_linux_amd64_#{version}.tar.gz"
  sha_filename: "#{repo}_#{version}_sha512-checksums.txt"
  filter:
  - "entity.system.os == 'linux'"
  - "entity.system.platform == 'ubuntu'"
  - "entity.system.platform_version.split('.')[0] == '22'"
  - "entity.system.arch == 'amd64'"

- platform: "xcp-ng8"
  arch: "amd64"
  asset_filename: "monitoring-plugins-debian8_linux_amd64_#{version}.tar.gz"
  sha_filename: "#{repo}_#{version}_sha512-checksums.txt"
  filter:
  - "entity.system.os == 'linux'"
  - "entity.system.platform == 'xcp-ng'"
  - "entity.system.platform_version.split('.')[0] == '8'"
  - "entity.system.arch == 'amd64'"

