FROM amazonlinux:2 as builder

ARG SENSU_GO_ASSET_NAME="monitoring-plugins-amazon"
ARG SENSU_GO_ASSET_VERSION="2.2.0"
ARG PLUGINS="check_http"

ADD create-sensu-asset /usr/bin/create-sensu-asset

WORKDIR /usr/lib64/nagios/plugins/

RUN amazon-linux-extras install -y epel && yum install -y which tar nagios-plugins-all
RUN create-sensu-asset -a $SENSU_GO_ASSET_NAME -b $PLUGINS -v $SENSU_GO_ASSET_VERSION -o /
