FROM debian:stretch as builder

ARG SENSU_GO_ASSET_NAME="monitoring-plugins-debian"
ARG SENSU_GO_ASSET_VERSION="2.2.0-2"
ARG PLUGINS="check_http"

ADD create-sensu-asset /usr/bin/create-sensu-asset

WORKDIR /usr/lib/nagios/plugins/

RUN apt-get update && apt-get install -y monitoring-plugins-basic
RUN create-sensu-asset -a $SENSU_GO_ASSET_NAME -b $PLUGINS -v $SENSU_GO_ASSET_VERSION -o /
