FROM alpine:latest as builder

ARG SENSU_GO_ASSET_NAME="monitoring-plugins-alpine"
ARG SENSU_GO_ASSET_VERSION="v2.2"
ARG PLUGINS="check_http"

ADD create-sensu-asset /usr/bin/create-sensu-asset

WORKDIR /usr/lib/monitoring-plugins/

RUN apk --update add bash monitoring-plugins coreutils libintl
RUN create-sensu-asset -a $SENSU_GO_ASSET_NAME -b $PLUGINS -v $SENSU_GO_ASSET_VERSION -o /
