name: Publish
on:
  push:
    tags:
      - '*'
jobs:
  build:
    name: Publish binaries
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: ./scripts/build_and_validate.sh
      env:
          ASSET_VERSION: ${{github.ref_name}}
          ASSET_REPONAME: monitoring-plugins
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: assets/*
        tag: ${{ github.ref_name }}
        overwrite: true
        file_glob: true

